"""Use case and functional requirement data for Report 3 (SRS).

Single source for the UC catalogue, the UC specifications, the FR tables and the
MF to UC to FR traceability matrix, so identifiers cannot drift between sections.
Built by build_srs.py.

Source labels used in the tables:
  US-nnn   backlog story, treklink-docs/_docs/03-backlog/02-user-stories.md
  Qnn      clarification answer, Session 8 (07-clarification-answers.md sections 1 to 3).
           Questions 30 to 73 are Recorded answers; requirements resting on them carry (P).
  S9-Qn    clarification answer, Session 9 (07-clarification-answers.md section 5), Confirmed
  D-nnn    decision register entry
  Enn-n    exception scenario, 05-main-flows.md
  FGT      04-firmware-ground-truth.md
"""

# ---------------------------------------------------------------------------
# Use cases
# id: (name, primary actors, main flows, one-line description)
# ---------------------------------------------------------------------------
UC = {
    1: ("Browse Trek Packages", "Guest, Customer", ["MF-01"],
        "List active trek packages with route, duration and price, filterable, without an account."),
    2: ("Submit Booking", "Customer", ["MF-01"],
        "Request a trip on a package for chosen dates and group size; the booking enters review."),
    3: ("Reserve Device", "Customer", ["MF-01"],
        "Hold a device for the booking while the form is completed; the hold expires if unused."),
    4: ("Confirm Booking", "Operator", ["MF-01"],
        "Review a submitted booking and confirm or reject it, seeing device and guide conflicts first."),
    5: ("Allocate Device", "Operator", ["MF-01"],
        "Bind specific physical devices to a confirmed booking or rental for the trip's time window."),
    6: ("Assign Guide", "Operator", ["MF-01"],
        "Assign one or more Guides to a trip whose dates do not overlap their other assignments."),
    7: ("Generate Rental Agreement", "Operator", ["MF-01"],
        "Produce the rental agreement PDF from the booking, allocation and pricing data."),
    8: ("Check Out Device", "Operator", ["MF-01"],
        "Hand the allocated devices to the Guide; the rental becomes Active and devices Rented."),
    9: ("Check In Device", "Operator", ["MF-05"],
        "Receive devices back from the Guide at trip end; returned devices become Returned."),
    10: ("Inspect Returned Device", "Operator", ["MF-05"],
         "Record condition, accessories and battery of a returned device, with any damage report."),
    11: ("Calculate Rental Charge", "Operator", ["MF-05"],
         "Compute base charge, late fee and damage fee, apply the deposit, and issue the invoice."),
    12: ("Process Payment", "Customer, Operator", ["MF-01", "MF-05"],
         "Pay into sandbox escrow at confirmation, then settle the balance or refund at return."),
    13: ("Ingest Field Event", "Gateway Bridge", ["MF-02"],
         "Accept a normalized mesh event, deduplicate it by eventId, persist it and route it by kind."),
    14: ("View Live Map", "Operator, Guide, Admin", ["MF-04"],
         "See live device positions, battery, last-seen and incidents, scoped by role on the server."),
    15: ("Acknowledge Incident", "Operator, Guide", ["MF-03"],
         "Take ownership of a Detected incident; the first acknowledgement fixes the MTTA timestamp."),
    16: ("Update Incident Status", "Operator, Admin, Guide", ["MF-03"],
         "Move an incident through In Progress, Resolved and Closed with a note on each step."),
    17: ("Record Response Note", "Guide, Operator", ["MF-03"],
         "Append a field or coordination note to an incident's audit trail."),
    18: ("Manage Users and Roles", "Admin", ["X"],
         "Create, deactivate and assign roles to accounts; maintain the Staff sub-role list."),
    19: ("Configure Business Parameters", "Admin", ["X"],
         "Change a registered business parameter at run time and see the change take effect."),
    20: ("View Audit Log", "Admin", ["X"],
         "Read the append-only authentication, device, incident and configuration audit trails."),
    21: ("Authenticate", "Customer, Operator, Guide, Admin", ["X"],
         "Log in, renew the session silently and log out."),
    22: ("Verify Device Availability", "(included)", ["MF-01"],
         "Check that enough allocatable devices exist for the requested window, under a row lock."),
    23: ("Send Notification", "(included)", ["MF-03"],
         "Push an incident alert or acknowledgement over WebSocket, and alerts by email, to the Guide and online Staff."),
    24: ("Apply Late Fee", "(extends UC-11)", ["MF-05"],
         "Add an itemized late fee when check-in is after the agreed return time plus grace."),
    25: ("Apply Damage Fee", "(extends UC-11)", ["MF-05"],
         "Add an itemized damage fee derived from the inspection's damage report."),
    26: ("Reopen Incident", "(extends UC-16)", ["MF-03"],
         "Return a Resolved incident to In Progress when new beacons arrive from the same episode."),
    27: ("Register Account", "Guest, Operator, Guide", ["MF-01"],
         "Create a Customer account by Google OAuth or email OTP, or on the customer's behalf."),
    28: ("Reset Password", "Customer, Operator, Guide, Admin", ["X"],
         "Reset a forgotten password by email OTP; an Operator may trigger it without seeing it."),
    29: ("Cancel Booking", "Customer, Operator", ["MF-01"],
         "Cancel a booking before check-out, releasing devices and applying the cancellation policy."),
    30: ("Extend Reservation Hold", "Operator", ["MF-01"],
         "Extend or disable the device hold on a Staff or Guide booking."),
    31: ("Manage Trek Packages", "Operator, Admin", ["MF-01"],
         "Create, edit and deactivate trek packages without changing confirmed bookings."),
    32: ("Create Trip", "Operator", ["MF-01"],
         "Create a dated trip from a package and prepare it for booking and provisioning."),
    33: ("Request Trip", "Guide", ["MF-01"],
         "Ask Staff to author a trip; the request becomes a Draft trip for an Operator."),
    34: ("Reschedule Trip", "Operator", ["MF-01"],
         "Move or cancel a trip before it starts, revalidating allocations and assignments."),
    35: ("Start Trip", "Operator, Guide", ["MF-04"],
         "Mark the group departed; the trip becomes Ongoing and its devices In-Field."),
    36: ("End Trip", "Operator, Guide", ["MF-05"],
         "Mark the trip Finished after the Guide has collected every device from the customers."),
    37: ("Confirm Device Handover", "Guide", ["MF-01"],
         "Complete the readiness checklist and confirm the devices received at check-out."),
    38: ("Register Device", "Admin", ["X"],
         "Enter a new physical device with its hardware version and firmware version."),
    39: ("Provision Channel Key", "Operator", ["MF-01"],
         "Load the fleet's custom LoRa channel key onto a device before its first check-out."),
    40: ("Report Missing Device", "Guide", ["MF-05"],
         "Report a device the Guide could not collect back from a customer."),
    41: ("Record Maintenance", "Operator", ["MF-05"],
         "Move a device into Maintenance with a reason, and back to Available when repaired."),
    42: ("Retire Device", "Admin", ["MF-05"],
         "Take a device permanently out of service, keeping its full history."),
    43: ("Sign Rental Agreement", "Customer", ["MF-01"],
         "Sign the agreement on the web; the signature is stamped into the PDF."),
    44: ("Approve Fee Waiver", "Operator", ["MF-05"],
         "Approve a fee waiver above the threshold, as a staff member other than the inspector."),
    45: ("View Booking History", "Customer", ["MF-01", "MF-05"],
         "See own bookings, rentals, agreements, deposits, invoices and payment status."),
    46: ("Dismiss Suspected Incident", "Operator", ["MF-03"],
         "Close a cadence-inferred incident judged a false alarm, with a dismissal reason."),
    47: ("Create Manual Incident", "Operator", ["MF-03"],
         "Open an incident for an emergency reported by phone or message, with no device SOS."),
    48: ("Trigger SOS", "TrekLink Device", ["MF-03"],
         "Broadcast an SOS by button, gesture or fall detection, followed by a position beacon."),
    49: ("Create Incident", "(extends UC-13)", ["MF-03"],
         "Open one Incident for a new SOS episode or a cadence anomaly, or append to the open one."),
    50: ("Manage Pricing Rules", "Admin", ["MF-05"],
         "Define base rates, deposit tiers, late-fee and damage-fee schedules for new agreements."),
    51: ("Manage Device Types", "Admin", ["X"],
         "Maintain the catalogue of device types, hardware versions and firmware versions."),
    52: ("View Reports", "Admin, Operator", ["MF-03", "MF-05"],
         "View and export device utilization and incident response-performance reports."),
    53: ("View System Health", "Admin", ["MF-04"],
         "See gateway connectivity, queue depth per tier and audit-log volume across the system."),
    54: ("Flush Offline Queue", "Gateway Bridge", ["MF-02"],
         "On reconnection, publish buffered events in strict priority order, resuming after a drop."),
    55: ("Expire Reservation Hold", "Scheduler", ["MF-01"],
         "Release a device hold that lapsed before the booking was submitted."),
    56: ("Mark Stale Device", "Scheduler", ["MF-04"],
         "Flag a device or gateway silent beyond its threshold as stale."),
    57: ("Escalate Unacknowledged Incident", "Scheduler", ["MF-03"],
         "Re-notify when an incident stays Detected beyond the auto-escalation timeout."),
    58: ("Escalate Unreturned Device", "Scheduler", ["MF-05"],
         "Escalate a rental whose device is still out past the non-return grace period."),
}

# ---------------------------------------------------------------------------
# UC specifications: trigger, precondition, postcondition, main steps,
# alternatives and exceptions, business rules
# ---------------------------------------------------------------------------
SPEC = {
    1: ("Guest or Customer opens the package catalogue",
        "At least one package is active",
        "None; read-only",
        ["The actor opens the catalogue.", "The system lists active packages with route, duration and base price.",
         "The actor filters by route, duration or price range and opens a package."],
        ["No package matches the filter: MSG01.", "Inactive packages are never listed (US-024)."],
        []),
    2: ("Customer selects Book on a package",
        "Customer is authenticated; package active",
        "Booking in `Sent`; hold converted into a pending reservation",
        ["The system creates the booking in `Start` and starts the device hold (UC-03).",
         "The Customer enters dates and group size, at most 6 fields per step.",
         "The system validates dates, group size and device availability (UC-22).",
         "The Customer submits; the booking moves to `Sent` for Operator review."],
        ["Hold lapses before submit: booking `Expired` (UC-55), MSG14.",
         "Dates overlap an existing allocation: rejected with the conflict named (E01-5), MSG12.",
         "Group size outside package limits: MSG02."],
        ["BR-01", "BR-25", "BR-26"]),
    3: ("Booking created in `Start`",
        "An allocatable device exists for the window",
        "One device held for the Customer for the hold duration",
        ["The system reserves one device count for the booking under a row lock.",
         "The hold timer starts at the configured duration."],
        ["Last device taken concurrently: the loser sees MSG11 and the booking stays without a device (E01-1).",
         "A Customer booking requests more than one device: rejected, MSG13."],
        ["BR-01", "BR-26", "BR-27"]),
    4: ("Operator opens a `Sent` booking",
        "Booking in `Sent`",
        "Booking `Pending` (confirmed) or `Rejected`",
        ["The system shows the booking with device availability (UC-22) and eligible Guides for the dates.",
         "The Operator confirms; the booking moves to `Pending` and the Customer is notified."],
        ["No eligible Guide or too few devices: conflict shown before confirm, confirm disabled (E01-4).",
         "Operator rejects with a mandatory reason: booking `Rejected`, reservation released, MSG16."],
        ["BR-02"]),
    5: ("Operator allocates devices to a confirmed booking or a rental",
        "Booking `Pending`, or rental `Created` without a booking",
        "Allocation records for each device; devices `Reserved` when the window is the next one",
        ["The Operator selects devices from the allocatable list.",
         "The system checks state, hardware version accepted by the trip, and window overlap in one transaction.",
         "The system shows the battery advisory or warning where it applies.",
         "The system saves the allocations."],
        ["Device in `Maintenance` or `Retired`: MSG17 (US-014).",
         "Window overlaps another allocation of the same device: MSG12.",
         "Hardware version not accepted by the trip: MSG18.",
         "Battery below the advisory or warning level: MSG19 or MSG20; allocation still allowed."],
        ["BR-01", "BR-04", "BR-05", "BR-28", "BR-29"]),
    6: ("Operator assigns Guides to a trip",
        "Trip in `On Prepare` or `On Booking`",
        "Guide assignments saved and visible on each Guide's view",
        ["The Operator selects users holding the Guide sub-role.",
         "The system checks each Guide has no overlapping trip and saves the assignment."],
        ["Selected user is not a Guide: MSG21.", "Guide already assigned to an overlapping trip: MSG12."],
        ["BR-02"]),
    7: ("Operator generates the agreement for a confirmed, allocated booking or rental",
        "Allocations exist; pricing rule in force",
        "Rental `Created` with an unsigned agreement PDF",
        ["The system composes the agreement from booking, allocation and pricing data.",
         "The system renders the PDF and records the generation in the audit log."],
        ["Agreement already signed: changes create an addendum, never an edit (US-030)."],
        ["BR-30"]),
    8: ("Operator starts check-out with the Guide present",
        "Agreement signed (UC-43); deposit paid (UC-12); each device provisioned (UC-39)",
        "Rental `Active`; devices `Rented`; booking `Completed`; trip `On Start` when all rentals are out",
        ["The system verifies signature, deposit and provisioning.",
         "The Guide confirms the device list and checklist (UC-37).",
         "The system moves each device `Reserved` to `Rented` through the FSM guard."],
        ["Deposit not paid: MSG22.", "Agreement unsigned: MSG23.", "Device not provisioned with the fleet key: MSG24.",
         "Guide's confirmed list differs: mismatch flagged for the Operator (US-033)."],
        ["BR-05", "BR-30", "BR-31"]),
    9: ("Guide brings the devices back",
        "Rental `Active` or `Escalated`; trip `Finished` or ending",
        "Returned devices `Returned`; check-in timestamp recorded; rental `Returned` when all are back",
        ["The Operator scans or selects each device presented by the Guide.",
         "The system records the check-in time and moves each device to `Returned`."],
        ["A device is missing: it stays `In-Field` and flagged; the Guide reports it (UC-40).",
         "A customer tries to return a device directly: refused, devices return only through the Guide (Q71)."],
        ["BR-05", "BR-32"]),
    10: ("Operator inspects a `Returned` device",
         "Device `Returned`",
         "Inspection result saved; damage report attached when damaged",
         ["The Operator records condition, accessories and battery.",
          "Where damaged, the Operator attaches a damage report with severity and evidence.",
          "The Operator marks the device serviceable or not."],
         ["Device fails inspection without any incident on the trip: still sent to `Maintenance` (E05-6)."],
         ["BR-33"]),
    11: ("All devices of a rental are inspected",
         "Rental `Returned`; inspections complete",
         "One immutable invoice itemizing base, late and damage charges",
         ["The system computes the base charge from the agreement's pricing terms.",
          "Late fee (UC-24) and damage fee (UC-25) are added when their conditions hold.",
          "The deposit is applied first; the balance or refund is computed.",
          "The system issues the invoice once per rental."],
         ["Damage fee exceeds the deposit: deposit consumed, balance invoiced, never a negative refund (E05-5).",
          "Fee waiver requested above the threshold: requires UC-44."],
         ["BR-17", "BR-20", "BR-21"]),
    12: ("Customer pays at confirmation, or balance or refund is due at return",
         "Booking `Pending`, or invoice issued",
         "Payment `Paid` or `Failed` with the sandbox flag set",
         ["The system creates a sandbox payment in `Pending`.",
          "The Customer completes the mock payment; an Operator records it for a rental without a booking.",
          "The system moves the payment to `Paid` and updates the booking or rental."],
         ["Payment fails: `Failed`, balance stays outstanding and visible, rental not closed (E05-4), MSG25."],
         ["BR-19", "BR-34"]),
    13: ("A normalized event reaches the backend over MQTT",
         "Gateway Bridge or node uplink connected to the broker",
         "Event persisted exactly once and routed, or discarded as a duplicate",
         ["The ingress adapter decodes the stock Meshtastic topic payload into the canonical envelope.",
          "The system derives `eventId = sha256(nodeNum : packetId)`.",
          "Inside one transaction the system inserts the event under a unique index on `eventId`.",
          "The system routes the event: SOS and cadence anomalies to UC-49, positions and telemetry to monitoring."],
         ["Duplicate `eventId`: no-op, audit row marks it duplicate (E02-2).",
          "Malformed payload: logged raw, counted, dropped; the loop continues (E02-4)."],
         ["BR-06"]),
    14: ("Operator, Guide or Admin opens the monitoring dashboard",
         "Actor authenticated",
         "None; read-only live view",
         ["The system opens one authenticated WebSocket connection.",
          "The server subscribes the connection only to the trips the role may see.",
          "The map renders markers by status with battery and last-seen, beside the incident queue."],
         ["Guide requests another Guide's trip: denied on the server (E04-5), MSG26.",
          "WebSocket drops: visible reconnecting state, resync on reopen (E04-3).",
          "Map provider unreachable: map error state, device and incident panels keep working (E04-6)."],
         ["BR-13", "BR-15", "BR-16", "BR-24"]),
    15: ("Actor selects Acknowledge on a Detected incident",
         "Incident `Detected`; actor is an Operator or the trip's assigned Guide",
         "Incident `Acknowledged`; MTTA timestamp fixed by the server",
         ["The actor presses Acknowledge, optionally adding a note: one step, at most 2 fields.",
          "The system performs `Detected` to `Acknowledged` and records actor, role, time and note."],
         ["Two actors acknowledge at once: first write wins; the second sees the state and who acknowledged (E03-3), MSG27.",
          "The other party acknowledges later: recorded in the audit trail without a transition."],
         ["BR-10", "BR-11"]),
    16: ("Actor changes an incident's status",
         "Incident not `Closed`",
         "Incident in the new state, one audit row per transition",
         ["The actor selects the next state and enters the required note.",
          "The system checks the transition table and the actor's authority and saves the transition."],
         ["Illegal transition: MSG28.", "Guide attempts `Resolved` or `Closed`: denied, MSG26.",
          "New beacons arrive after `Resolved`: UC-26 applies."],
         ["BR-10", "BR-11", "BR-12"]),
    17: ("Actor adds a note to an incident",
         "Incident exists and is not `Closed`",
         "Note appended to the audit trail, attributed by role",
         ["The actor writes the note.", "The system appends it with actor, role and server time."],
         ["Attempt to edit or delete an earlier entry: no such operation exists (BR-11)."],
         ["BR-11"]),
    18: ("Admin opens account management",
         "Admin authenticated",
         "Account created, deactivated or re-roled; change audited",
         ["The Admin lists accounts by role and active flag.",
          "The Admin creates a Staff account, changes a sub-role, or deactivates an account.",
          "Deactivation revokes the account's refresh tokens immediately."],
         ["Non-Admin attempts a role change: MSG26."],
         ["BR-14", "BR-35"]),
    19: ("Admin edits a business parameter",
         "Parameter registered in the Configuration Matrix",
         "New value in force without a redeploy; change audited",
         ["The Admin selects a parameter and enters a new value.",
          "The system validates type and range, saves it and records the change.",
          "Dependent behaviour uses the new value from the next evaluation."],
         ["Value out of range: MSG02."],
         ["BR-23"]),
    20: ("Admin opens the audit log",
         "Admin authenticated",
         "None; read-only",
         ["The Admin filters by trail, actor and date range.", "The system lists entries; no edit or delete exists."],
         [],
         ["BR-11"]),
    21: ("User opens the sign-in page, or a token expires",
         "Account active",
         "Session with an access token and a rotating refresh token, or signed out",
         ["The user signs in with username or linked email and password, or with Google.",
          "The system issues a short-lived access token and a refresh token.",
          "The client renews silently; logout revokes the refresh token."],
         ["Invalid credentials: MSG09, without saying which field was wrong.",
          "Refresh token reused after rotation: whole token family revoked, re-login forced."],
         ["BR-14"]),
    22: ("Included by UC-02, UC-04 and UC-05", "", "", [
         "The system counts allocatable devices for the window, excluding `Maintenance`, `Retired` and overlapping allocations, under a row lock."],
         [], ["BR-01"]),
    23: ("Included by UC-49, UC-47 and UC-15", "", "", [
         "The system persists the incident first, then pushes over WebSocket to the assigned Guide and all online Operators and Admins, and sends email.",
         "Clients offline at the time reconcile on reconnect (E03-7)."],
         [], []),
    24: ("Extends UC-11 when check-in is later than the agreed return time plus grace", "", "", [
         "The system computes the late fee from the configured rate and adds it as its own invoice line (E05-1)."],
         [], ["BR-18"]),
    25: ("Extends UC-11 when an inspection carries a damage report", "", "", [
         "The system computes the damage fee from the damage-fee schedule and links it to the damage report (E05-2)."],
         [], ["BR-17"]),
    26: ("Extends UC-16 when beacons of the same episode arrive after `Resolved`", "", "", [
         "The system moves the incident `Resolved` to `In Progress`, records the reopen with its cause, and notifies (E03-6)."],
         [], ["BR-12"]),
    27: ("Guest selects Register, or an Operator or Guide creates an account for a customer",
         "Email not already registered",
         "Active Customer account",
         ["The Guest signs up with Google OAuth, or with an email verified by OTP.",
          "The system derives the username from the email local part and creates the Customer account.",
          "Alternative flow: a Guide verifies the customer by phone or message, then an Operator or Guide creates the account."],
         ["Email already registered: MSG10.", "OTP expired or wrong: MSG08.",
          "Derived username taken: the system appends a numeric suffix."],
         ["BR-35", "BR-36"]),
    28: ("User selects Forgot password, or an Operator triggers a reset for a verified customer",
         "Account exists",
         "Password changed; reset token consumed",
         ["The system sends a single-use, time-limited OTP to the registered email.",
          "The user enters the OTP and a new password; the system stores only its hash."],
         ["Unknown email: the same response as a known one, revealing nothing.",
          "Expired or used token: MSG08, nothing changes.",
          "An Operator never sees or sets the password; the reset goes to the registered email only."],
         ["BR-36"]),
    29: ("Customer or Operator cancels a booking",
         "Booking in `Start`, `Sent` or `Pending`",
         "Booking `Cancelled`; devices released; refund or fee applied",
         ["The actor requests cancellation.",
          "The system computes the cancellation fee: none within the free window after payment, otherwise the configured percentage of the rental fee.",
          "The system refunds the escrow minus the fee and releases the allocations."],
         ["After check-out: cancellation not offered; the trip-end flow applies."],
         ["BR-03"]),
    30: ("Operator edits the hold on a Staff or Guide booking",
         "Booking in `Start`",
         "Hold extended or disabled",
         ["The Operator extends the hold by a duration or disables it.", "The system records the change."],
         ["Customer booking: extension not available (Q59)."],
         ["BR-27"]),
    31: ("Operator or Admin edits the package catalogue",
         "Actor authorized",
         "Package saved; confirmed bookings keep their agreed terms",
         ["The actor enters route, duration, base price, device requirements and limits.",
          "The system saves the package with an active flag."],
         ["Editing a package with confirmed bookings: those bookings keep their terms (US-023)."],
         ["BR-30"]),
    32: ("Operator creates a trip, or opens a Guide's trip request",
         "Package exists",
         "Trip in `Draft`",
         ["The Operator selects a package and dates and sets guides-per-trip and accepted hardware versions.",
          "The system creates the trip in `Draft`, then `On Prepare` when the Operator starts provisioning."],
         [],
         ["BR-28"]),
    33: ("Guide requests a trip", "Guide authenticated", "Trip request visible to Operators",
         ["The Guide enters package, dates and group details.", "The system records the request for an Operator (UC-32)."],
         [], []),
    34: ("Operator reschedules or cancels a trip",
         "Trip in any state before `Ongoing`",
         "Trip dates changed with allocations revalidated, or trip `Cancelled` with bookings refunded per policy",
         ["The Operator enters new dates.", "The system revalidates device allocations and Guide assignments for the new window."],
         ["A device or Guide conflicts in the new window: listed for the Operator to resolve.",
          "Trip cancelled: bookings cancelled and refunded per BR-03; allocations released."],
         ["BR-01", "BR-03"]),
    35: ("Operator or assigned Guide starts the trip",
         "Trip `On Start`; all rentals `Active`",
         "Trip `Ongoing`; its devices `In-Field`",
         ["The actor selects Start Trip.", "The system moves the trip to `Ongoing` and each device `Rented` to `In-Field`."],
         [],
         ["BR-05"]),
    36: ("Operator or Guide ends the trip",
         "Trip `Ongoing` or `Emergency`",
         "Trip `Finished`; missing devices listed",
         ["The Guide collects every device from the customers.", "The actor selects End Trip; the system moves the trip to `Finished`."],
         ["Devices missing: the Guide reports them (UC-40) before or after ending."],
         ["BR-32"]),
    37: ("Guide opens the handover step at check-out",
         "Check-out in progress",
         "Guide confirmation recorded with time and account",
         ["The system shows the allocated devices, battery advisories and the readiness checklist.",
          "The Guide verifies each device and confirms."],
         ["Device fails the Guide's check: handover rejected for that device, device to `Maintenance`, Operator re-allocates (E01-3).",
          "Battery below the warning level: the Guide must confirm manual verification (BR-04)."],
         ["BR-04", "BR-31"]),
    38: ("Admin registers a new unit",
         "Device type exists in the catalogue",
         "Device `Available`",
         ["The Admin enters device ID, device type, hardware version and firmware version.",
          "The system creates the device in `Available` with empty telemetry."],
         ["Device ID exists: MSG10."],
         ["BR-05"]),
    39: ("Operator provisions a device",
         "Device registered",
         "Device marked provisioned with the fleet channel key",
         ["The Operator loads the fleet key onto the device using the provisioning tool.",
          "The system records that the device is provisioned; the key itself is never shown again or logged."],
         [],
         ["BR-31"]),
    40: ("Guide reports a device not recovered",
         "Device allocated to the Guide's trip",
         "Missing report open; rental flagged",
         ["The Guide selects the device and describes the circumstances.", "The system flags the rental and notifies Operators."],
         ["Device found later: the Operator checks it in normally (UC-09)."],
         ["BR-22"]),
    41: ("Operator moves a device to or from Maintenance",
         "Device `Available` or `Returned` (to enter); `Maintenance` (to leave)",
         "Device `Maintenance` with a record, or back to `Available`",
         ["The Operator enters a reason and an optional expected return date.",
          "When repaired, the Operator returns the device to `Available`."],
         ["Unrepairable: the Admin retires it (UC-42)."],
         ["BR-05", "BR-33"]),
    42: ("Admin retires a device",
         "Device not on an active allocation",
         "Device `Retired`, terminal; history retained",
         ["The Admin selects Retire and a reason.", "The system moves the device to `Retired`."],
         ["Active allocation exists: MSG29."],
         ["BR-05", "BR-22"]),
    43: ("Customer opens the agreement at check-out",
         "Agreement generated",
         "Agreement signed; signature stamped into the PDF",
         ["The Customer reviews the PDF and draws a signature.",
          "The system stamps the signature into the PDF and records the signing."],
         ["Customer without an account: the Operator or Guide captures the signature on the staff device (S9-Q21)."],
         ["BR-30"]),
    44: ("A waiver above the threshold is requested",
         "Invoice pending; waiver requested",
         "Waiver approved or refused",
         ["An Operator who did not inspect the device reviews and approves or refuses the waiver."],
         ["Approver is the inspector: refused, MSG30 (E05-7)."],
         ["BR-21"]),
    45: ("Customer opens My bookings", "Customer authenticated", "None; read-only",
         ["The system lists the Customer's own bookings and rentals in reverse order, with agreement, deposit, invoice and payment status."],
         ["A Customer requests another customer's record: MSG26."],
         ["BR-37"]),
    46: ("Operator dismisses a Suspected incident",
         "Incident `Detected` with confidence `Suspected`",
         "Incident `Closed` with the dismissal recorded",
         ["The Operator selects Dismiss and a dismissal reason, one step.",
          "The system performs `Detected` to `Closed` and writes the audit row."],
         ["The SOS text frame arrives late: the incident is upgraded to `Confirmed` in place and dismissal is no longer offered (US-088)."],
         ["BR-09", "BR-11"]),
    47: ("Operator opens an incident by hand", "Operator authenticated", "Incident `Detected`, marked Staff-initiated",
         ["The Operator enters the report, optionally linking a device or trip.",
          "The system creates the incident and notifies (UC-23)."],
         [], ["BR-10"]),
    48: ("Button, 3-second gesture, or fall detection after its pre-alarm countdown",
         "Device powered, on the mesh",
         "SOS position and text packets broadcast; beacon running",
         ["The device sends a position packet, then the `SOS - ...` text once.",
          "The device beacons its position every 5 s for the first minute, then every 30 s (FGT §2)."],
         ["Text frame lost over RF: the backend infers a Suspected episode from beacon cadence (E03-1).",
          "Cancel on the device: stops the local alarm only; nothing is transmitted (FGT §2)."],
         ["BR-08", "BR-09"]),
    49: ("Extends UC-13 when an event is an SOS text or crosses the cadence threshold", "", "", [
         "If an open incident exists for that device within the correlation window, the system appends the event to it.",
         "Otherwise it creates one Incident in `Detected` with confidence `Confirmed` (SOS text) or `Suspected` (cadence), linked to device, trip and eventId, and includes UC-23.",
         "An SOS from a device with no active trip still creates the incident, flagged unassigned (E03-4)."],
         [], ["BR-08", "BR-09"]),
    50: ("Admin edits pricing", "Admin authenticated", "Rule saved; applies to new agreements only",
         ["The Admin sets base rates per package, device type or pack, deposit tiers, late-fee and damage-fee schedules."],
         ["Rule change never alters a signed agreement (US-067)."], ["BR-17", "BR-18", "BR-23"]),
    51: ("Admin edits the device type catalogue", "Admin authenticated", "Catalogue updated",
         ["The Admin adds or edits a device type with hardware version and firmware version."],
         ["Deleting a type that has devices: refused, MSG29."], []),
    52: ("Admin or Operator opens Reports", "Actor authorized", "None; read-only, CSV export available",
         ["The actor chooses a report and date range.", "The system derives it from rental, device and incident audit data."],
         [], []),
    53: ("Admin opens System Health", "Admin authenticated", "None; read-only",
         ["The system shows each gateway's last sync, queue depth per tier and retry count, and audit-log volume."],
         [], ["BR-15"]),
    54: ("Uplink returns after an outage", "Queue holds unsent events", "Every queued event published once, in order",
         ["The gateway publishes events ordered by priority tier, then by queue sequence.",
          "A row is marked flushed only after the broker acknowledges it."],
         ["Uplink drops mid-flush: unacknowledged rows stay queued; flush resumes from the head (E02-1).",
          "Queue reached its bound during the outage: P3 shed first, never P0, and logged (E02-5)."],
         ["BR-07"]),
    55: ("Hold timer lapses", "Booking in `Start`", "Booking `Expired`; device released",
         ["The system releases the held device and moves the booking to `Expired`."], [], ["BR-27"]),
    56: ("Scheduled check", "Device or gateway has reported before", "Stale flag set; markers age visibly",
         ["The system flags each device and gateway silent beyond its configured threshold, keeping last-seen visible."],
         [], ["BR-15"]),
    57: ("Scheduled check", "Incident `Detected`", "Escalation notification sent",
         ["The system re-notifies Operators and Admins when an incident stays `Detected` past the auto-escalation timeout."],
         [], []),
    58: ("Scheduled check", "Rental `Active` past the agreed return time", "Rental `Escalated`",
         ["When a device is still out past the non-return grace period, the system moves the rental to `Escalated` and notifies Operators.",
          "After the Operator records the loss, the device is retired with a loss record and the rental can close."],
         [], ["BR-22"]),
}

# include / extend relations: (base, kind, target)
REL = [
    (2, "include", 22), (4, "include", 22), (5, "include", 22),
    (8, "include", 7), (8, "include", 43), (8, "include", 37),
    (49, "include", 23), (47, "include", 23), (15, "include", 23),
    (24, "extend", 11), (25, "extend", 11), (44, "extend", 11),
    (26, "extend", 16), (49, "extend", 13),
]

# ---------------------------------------------------------------------------
# Functional requirements: (id, EARS text, UC ids, MFs, source)
# (P) at the end of the source marks a requirement resting on a Recorded answer.
# ---------------------------------------------------------------------------
FR = [
    # --- Identity and access
    ("FR-AUTH-01", "WHEN a mutating request is received, the system SHALL require both a valid JWT and a CASL policy that permits the action, and SHALL return 401 or 403 in the standard envelope otherwise.", [21], ["X"], "US-008, BR-14"),
    ("FR-AUTH-02", "WHEN a Guest registers with Google OAuth or with an email verified by OTP, the system SHALL create an active Customer account whose username is the email local part, with a numeric suffix where that username is taken.", [27], ["MF-01"], "Q31, Q41 (P)"),
    ("FR-AUTH-03", "WHILE a Guide is authenticated, the system SHALL restrict every read of trips, devices, positions and incidents, over REST and WebSocket, to trips assigned to that Guide.", [14, 15, 16], ["MF-03", "MF-04"], "US-037, US-038, E04-5"),
    ("FR-AUTH-04", "WHERE a customer has no account, the system SHALL let an Operator or a Guide create the Customer account on the customer's behalf after identity verification.", [27], ["MF-01"], "Q31 (P)"),
    ("FR-AUTH-05", "WHEN valid credentials are submitted, the system SHALL issue a short-lived access token and a refresh token; IF credentials are invalid, THEN the system SHALL return 401 without revealing which field was wrong.", [21], ["X"], "US-003"),
    ("FR-AUTH-06", "WHEN a valid refresh token is presented, the system SHALL issue a new access token and rotate the refresh token; IF a rotated refresh token is reused, THEN the system SHALL revoke the whole token family.", [21], ["X"], "US-005"),
    ("FR-AUTH-07", "WHEN a user logs out, the system SHALL revoke the presented refresh token immediately.", [21], ["X"], "US-006"),
    ("FR-AUTH-08", "WHEN a password reset is requested, the system SHALL send a single-use, time-limited OTP to the registered email only and SHALL respond identically for unknown emails; an Operator SHALL be able to trigger a reset and SHALL NOT be able to view or set the password.", [28], ["X"], "US-007, Q35 (P)"),
    ("FR-AUTH-09", "The system SHALL store roles, Staff sub-roles and permissions as data, and a permission change SHALL take effect on the next request without a redeploy.", [18], ["X"], "US-001, Q33 (P), S9-Q2"),
    ("FR-AUTH-10", "WHEN an Admin deactivates an account, the system SHALL set `isActive` to false and reject that account's refresh tokens immediately.", [18], ["X"], "US-009, Q45 (P)"),
    ("FR-AUTH-11", "The system SHALL record every authentication event (login, logout, failed attempt, reset) with actor, event type, IP and UTC timestamp, append-only, and SHALL NOT store an attempted password in any form.", [20, 21], ["X"], "US-004, Q46 (P)"),
    ("FR-AUTH-12", "WHILE a Customer is authenticated, the system SHALL restrict that Customer's reads of bookings, rentals, agreements and invoices to records the Customer owns.", [45], ["MF-01", "MF-05"], "US-039, US-070"),
    ("FR-AUTH-13", "WHEN a record is deleted, the system SHALL mark it deleted and retain it, except where hard deletion is specified for that record type.", [18], ["X"], "Q36 (P)"),
    ("FR-AUTH-14", "The system SHALL let a Guest browse active packages without an account, and SHALL require an account to submit a booking.", [1, 2], ["MF-01"], "Q30 (P)"),
    ("FR-AUTH-15", "The system SHALL grant an Admin every permission of an Operator in addition to the administration functions.", [16, 18], ["X"], "S9-Q2"),
    # --- Device fleet
    ("FR-DEV-01", "The system SHALL change device state only through the transition table of the 7-state device FSM, SHALL reject any other change with 409, and SHALL write an append-only audit row for each transition.", [5, 8, 9, 35, 41, 42], ["MF-01", "MF-05"], "US-013, BR-05"),
    ("FR-DEV-02", "WHEN an Admin registers a device with a unique device ID, a device type, a hardware version and a firmware version, the system SHALL create it in `Available`; IF the device ID exists, THEN the system SHALL reject it with 409.", [38], ["X"], "US-012, Q49 (P)"),
    ("FR-DEV-03", "The system SHALL let an Admin maintain device types with hardware and firmware versions, and SHALL refuse to delete a type that has registered devices.", [51], ["X"], "US-011"),
    ("FR-DEV-04", "WHERE a trip restricts accepted hardware versions, the system SHALL reject allocation of a device whose hardware version the trip does not accept.", [5, 32], ["MF-01"], "Q50 (P)"),
    ("FR-DEV-05", "WHEN a device below the advisory battery level is allocated or checked out, the system SHALL show a charge-before-departure advisory; IF the level is below the warning level, THEN the system SHALL require the Operator or Guide to confirm manual verification. The system SHALL NOT block allocation or check-out on battery level.", [5, 8, 37], ["MF-01"], "Q52 (P), S9-Q28, BR-04"),
    ("FR-DEV-06", "WHILE a device is in `Maintenance` or `Retired`, the system SHALL reject any allocation referencing it, inside the same transaction as the allocation write.", [5], ["MF-01"], "US-014"),
    ("FR-DEV-07", "The system SHALL allow one device to hold several allocations whose time windows do not overlap, and SHALL reject an allocation whose window overlaps an existing one for that device.", [5], ["MF-01"], "Q53 (P), S9-Q4, E01-5"),
    ("FR-DEV-08", "WHEN a telemetry or position event is ingested, the system SHALL update the device's battery, last-seen time and last position, and SHALL discard a reading older than the stored last-seen time.", [13], ["MF-02", "MF-04"], "US-017"),
    ("FR-DEV-09", "IF a device remains unreturned beyond the non-return grace period, THEN the system SHALL move its rental to `Escalated`, and WHEN an Operator records the loss, the system SHALL move the device to `Retired` with a loss record.", [58, 40, 42], ["MF-05"], "BR-22, E05-3, S9-Q27"),
    ("FR-DEV-10", "WHEN an Operator moves a device to `Maintenance`, the system SHALL require a reason, accept an optional expected return date, and keep the device unallocatable until it is moved back to `Available`.", [41], ["MF-05"], "US-018"),
    ("FR-DEV-11", "WHEN an Admin retires a device, the system SHALL set the terminal state `Retired` without deleting the device or its history; IF the device has an active allocation, THEN the system SHALL reject the retirement.", [42], ["MF-05"], "US-020"),
    ("FR-DEV-12", "The system SHALL present a read-only chronological history per device of allocations, rentals, incidents, damage and maintenance, each entry with actor, event type and UTC time.", [42], ["MF-05"], "US-022, Q54 (P)"),
    ("FR-DEV-13", "The system SHALL block check-out of a device not yet provisioned with the fleet channel key, and SHALL never display, return or log the key after it is entered.", [39, 8], ["MF-01"], "D-021, Q51 (P)"),
    ("FR-DEV-14", "WHEN an Operator attaches a damage report to a `Returned` device, the system SHALL store description, severity and evidence reference permanently and SHALL leave the device state unchanged.", [10], ["MF-05"], "US-019"),
    # --- Booking and rental
    ("FR-BOOK-01", "WHEN a Customer submits a booking, the system SHALL validate package, dates and group size against the package limits and SHALL move the booking from `Start` to `Sent`.", [2], ["MF-01"], "US-025, S9-Q25"),
    ("FR-BOOK-02", "The system SHALL let a device be committed to at most one booking or rental for any overlapping time window, using a row-level lock, and the losing request SHALL receive an unavailable result without an oversell.", [3, 5, 22], ["MF-01"], "BR-01, E01-1, Q58 (P)"),
    ("FR-BOOK-03", "WHEN a Customer creates a booking, the system SHALL reserve exactly one device; WHERE the booking is made by a Guide or an Operator, the system SHALL allow several devices up to the package limit.", [3], ["MF-01"], "US-026, Q57 (P)"),
    ("FR-BOOK-04", "The system SHALL allow an Operator to confirm a booking only when enough allocatable devices and an eligible Guide exist for its dates, and SHALL show any conflict before confirmation.", [4], ["MF-01"], "BR-02, E01-4"),
    ("FR-BOOK-05", "WHEN a Customer booking enters `Start`, the system SHALL hold its device for the configured hold duration and SHALL move the booking to `Expired` and release the device when the hold lapses; WHERE the booking is a Staff or Guide booking, an Operator SHALL be able to extend or disable the hold.", [3, 30, 55], ["MF-01"], "Q59 (P), S9-Q25"),
    ("FR-BOOK-06", "WHEN an Operator rejects a booking, the system SHALL require a reason, move the booking to `Rejected` and release its reservation.", [4], ["MF-01"], "US-027"),
    ("FR-BOOK-07", "WHEN a booking is cancelled, the system SHALL refund the escrow in full within the configured free-cancellation window after payment, and otherwise SHALL retain the configured percentage of the rental fee, not of the trip fee; the booking SHALL move to `Cancelled` and its devices SHALL be released.", [29, 34], ["MF-01"], "BR-03, Q60 (P), E01-2"),
    ("FR-BOOK-08", "The system SHALL let an Operator or Guide create a rental without a booking for a customer provisioned by Staff or a Guide.", [5, 7, 8], ["MF-01"], "Q55 (P)"),
    ("FR-BOOK-09", "WHEN an Operator generates a rental agreement, the system SHALL compose it from booking, allocation and pricing data as a PDF, and SHALL make it immutable once check-out begins, recording later changes as an addendum.", [7], ["MF-01"], "US-030, Q62 (P)"),
    ("FR-BOOK-10", "WHEN a rental agreement is signed, the system SHALL stamp the drawn signature into the PDF, record the signing in the audit log and mark the agreement signed.", [43], ["MF-01"], "Q62 (P), S9-Q21"),
    ("FR-BOOK-11", "WHEN check-out completes, the system SHALL require a signed agreement, a paid deposit, provisioned devices and the Guide's handover confirmation, SHALL move each device `Reserved` to `Rented`, the rental to `Active` and the booking to `Completed`.", [8, 37], ["MF-01"], "US-031, US-032, US-033, S9-Q25, S9-Q27"),
    ("FR-BOOK-12", "IF the Guide's confirmed device list differs from the allocated list, THEN the system SHALL flag the mismatch and hold check-out until an Operator resolves it.", [37], ["MF-01"], "US-033"),
    ("FR-BOOK-13", "WHEN check-in completes, the system SHALL record the check-in time, move each presented device to `Returned`, keep any device not presented `In-Field` and flagged, and accept devices only from the Guide or an Operator.", [9], ["MF-05"], "US-034, Q71 (P)"),
    ("FR-BOOK-14", "The system SHALL let an Operator disable a Customer booking or transfer it to Guide provisioning when the Customer breaches the terms.", [29], ["MF-01"], "Q59 (P)"),
    ("FR-BOOK-15", "The system SHALL change booking state only through the booking FSM (`Start`, `Sent`, `Pending`, `Completed`, `Expired`, `Rejected`, `Cancelled`) and SHALL reject any other change.", [2, 4, 29, 55], ["MF-01"], "Q56 (P), S9-Q25"),
    ("FR-BOOK-16", "The system SHALL change rental state only through the rental FSM (`Created`, `Active`, `Returned`, `Closed`, `Escalated`) and SHALL reject any other change.", [7, 8, 9, 11, 58], ["MF-01", "MF-05"], "S9-Q27"),
    # --- Trips
    ("FR-TRIP-01", "WHEN an Operator creates a trip from a package and dates, the system SHALL create it in `Draft` with its guides-per-trip setting and accepted hardware versions.", [32], ["MF-01"], "Q65, Q68 (P)"),
    ("FR-TRIP-02", "WHEN a Guide requests a trip, the system SHALL record the request for an Operator to author as a trip.", [33], ["MF-01"], "Q65 (P)"),
    ("FR-TRIP-03", "The system SHALL change trip state only through the trip FSM (`Draft`, `On Prepare`, `On Booking`, `On Start`, `Ongoing`, `Finished`, `Cancelled`, `Emergency`) and SHALL reject any other change.", [32, 34, 35, 36], ["MF-01", "MF-04", "MF-05"], "Q66 (P), S9-Q5, S9-Q26"),
    ("FR-TRIP-04", "WHEN an Operator assigns a Guide, the system SHALL accept only users holding the Guide sub-role and SHALL reject an assignment that overlaps another trip of that Guide.", [6], ["MF-01"], "US-029, Q44 (P)"),
    ("FR-TRIP-05", "WHEN a trip is rescheduled before `Ongoing`, the system SHALL revalidate its allocations and Guide assignments for the new window and list every conflict; WHEN it is cancelled, the system SHALL cancel its bookings under FR-BOOK-07 and release its allocations.", [34], ["MF-01"], "Q72 (P)"),
    ("FR-TRIP-06", "WHEN an Operator or the assigned Guide starts a trip in `On Start`, the system SHALL move it to `Ongoing` and each of its devices `Rented` to `In-Field`.", [35], ["MF-04"], "S9-Q4, S9-Q26, US-032"),
    ("FR-TRIP-07", "WHEN an Operator or Guide ends a trip, the system SHALL move it to `Finished` and list every device not yet checked in.", [36], ["MF-05"], "Q71 (P)"),
    ("FR-TRIP-08", "The system SHALL let only an Operator move an `Ongoing` trip to `Emergency`, and SHALL flag, without transition, a trip that has an open incident.", [16], ["MF-03"], "S9-Q5"),
    ("FR-TRIP-09", "The system SHALL require the assigned Guide to complete the configured readiness checklist before check-out completes.", [37], ["MF-01"], "Q73 (P)"),
    ("FR-TRIP-10", "The system SHALL track each trip participant by device, by customer account or by booking.", [32], ["MF-01"], "Q69 (P)"),
    ("FR-TRIP-11", "WHEN a trek package is created or edited, the system SHALL store route, duration, base price, device requirements and an active flag, and SHALL leave confirmed bookings on their agreed terms.", [31], ["MF-01"], "US-023, Q70 (P)"),
    ("FR-TRIP-12", "WHILE a Guide is authenticated, the system SHALL show that Guide's assigned trips with roster and allocated devices.", [14], ["MF-01", "MF-04"], "US-037, US-010"),
    # --- Gateway and synchronization
    ("FR-EVT-01", "WHEN a field event is ingested, the system SHALL derive `eventId = sha256(nodeNum : packetId)`, insert it under a database unique index inside the same transaction as its side effects, and treat a repeated `eventId` as a no-op.", [13], ["MF-02"], "BR-06, US-050, D-006, E02-2"),
    ("FR-EVT-02", "WHEN the gateway parses a mesh event, it SHALL classify it P0 (SOS), P1 (incident location), P2 (GPS) or P3 (telemetry) and persist it to its local queue before any network attempt.", [13, 54], ["MF-02"], "US-044, US-043"),
    ("FR-EVT-03", "WHEN the uplink is restored, the gateway SHALL flush queued events ordered by priority tier and then by queue sequence, so that every P0 event is sent before any P1, P2 or P3 event.", [54], ["MF-02"], "BR-07, US-048"),
    ("FR-EVT-04", "The gateway SHALL mark a queued event flushed only after the broker acknowledges it; IF the uplink drops mid-flush, THEN unacknowledged events SHALL stay queued and the flush SHALL resume from the queue head.", [54], ["MF-02"], "US-047, E02-1"),
    ("FR-EVT-05", "WHEN an SOS event arrives for a device with an open incident inside the correlation window, the system SHALL append it to that incident; otherwise the system SHALL create exactly one new incident.", [49], ["MF-03"], "BR-08, E03-2, E03-5"),
    ("FR-EVT-06", "WHEN a device's position events reach the configured count N within window W, the system SHALL raise a `Suspected` incident at lower confidence.", [49], ["MF-03"], "BR-09, E03-1, D-007"),
    ("FR-EVT-07", "IF a payload cannot be decoded, THEN the system SHALL log it raw, count it, drop it and continue without blocking the queue head.", [13], ["MF-02"], "E02-4"),
    ("FR-EVT-08", "WHILE the gateway queue is at its configured bound, the gateway SHALL shed P3 events first and SHALL never shed P0, logging every shed event.", [54], ["MF-02"], "E02-5"),
    ("FR-EVT-09", "WHEN the gateway restarts with a non-empty queue, it SHALL retain every queued event and SHALL NOT mint a new `eventId` for any of them.", [54], ["MF-02"], "E02-3"),
    ("FR-EVT-10", "The system SHALL order events by queue sequence and priority, never by wall-clock comparison across hosts, and SHALL treat a device `rx_time` of 0 as unknown.", [13, 54], ["MF-02"], "E02-6, FGT §3"),
    ("FR-EVT-11", "WHEN a text event is decoded, the system SHALL test the `SOS - FALL DETECTED` prefix before the `SOS - ` prefix and SHALL classify both as SOS.", [13, 49], ["MF-02", "MF-03"], "FGT §2"),
    ("FR-EVT-12", "The system SHALL accept events from the stock Meshtastic MQTT topics `<root>/2/json/...` and `<root>/2/e/...` through ingress adapters that produce one canonical event envelope.", [13], ["MF-02"], "D-007, D-019, FGT §4"),
    ("FR-EVT-13", "The system SHALL write one append-only synchronization audit row per ingestion attempt, recording acceptance or duplicate rejection.", [13], ["MF-02"], "US-051"),
    ("FR-EVT-14", "The system SHALL report per gateway the queue depth for each tier, the last sync time and the retry count of the oldest queued event.", [53], ["MF-02", "MF-04"], "US-049"),
    ("FR-EVT-15", "IF an incoming `eventId` is already queued or flushed at the gateway, THEN the gateway SHALL discard it without re-inserting.", [13], ["MF-02"], "US-045"),
    ("FR-EVT-16", "WHEN a late SOS text frame matches an open `Suspected` incident, the system SHALL upgrade that incident to `Confirmed` in place.", [49], ["MF-03"], "US-088"),
    # --- Incidents
    ("FR-INC-01", "WHEN an incident is created, the system SHALL link it to the originating device, trip and `eventId`; IF the device has no active trip, THEN the system SHALL still create it and flag it unassigned.", [49], ["MF-03"], "US-057, E03-4"),
    ("FR-INC-02", "The system SHALL change incident state only through the 5-state incident FSM, and each transition SHALL record actor ID and role, UTC server time and note.", [15, 16, 46], ["MF-03"], "BR-10, US-054"),
    ("FR-INC-03", "WHEN an Operator or the trip's assigned Guide acknowledges a `Detected` incident, the system SHALL perform `Detected` to `Acknowledged` with the server timestamp used for MTTA; a later acknowledgement by the other party SHALL be recorded without a transition.", [15], ["MF-03"], "US-060, US-063, S9-Q7"),
    ("FR-INC-04", "The system SHALL keep the incident audit trail append-only and SHALL expose no operation that edits or deletes an entry.", [17, 20], ["MF-03"], "BR-11, US-059"),
    ("FR-INC-05", "IF two actors acknowledge the same incident concurrently, THEN the first write SHALL win and the second actor SHALL be shown the current state and the acknowledging actor.", [15], ["MF-03"], "E03-3"),
    ("FR-INC-06", "WHEN beacons of the same episode arrive after `Resolved`, the system SHALL move the incident back to `In Progress` and record the reopen; WHEN they arrive after `Closed`, the system SHALL open a new incident.", [26], ["MF-03"], "BR-12, E03-6, S9-Q6"),
    ("FR-INC-07", "WHEN an incident moves to `In Progress`, the system SHALL require a non-empty note and SHALL accept the change only from an Operator, an Admin or the assigned Guide.", [16], ["MF-03"], "US-061, S9-Q7"),
    ("FR-INC-08", "WHEN an incident moves to `Resolved` or `Closed`, the system SHALL require a resolution note for `Resolved`, accept the change only from an Operator or Admin, and use the `Resolved` timestamp for MTTR.", [16], ["MF-03"], "US-062, S9-Q7"),
    ("FR-INC-09", "WHEN an Operator dismisses a `Suspected` incident, the system SHALL perform `Detected` to `Closed` in one step with a dismissal reason and write an audit row marking a false positive.", [46], ["MF-03"], "US-088, S9-Q6"),
    ("FR-INC-10", "WHEN an Operator creates an incident by hand, the system SHALL create it in `Detected`, optionally linked to a device or trip, and mark it Staff-initiated.", [47], ["MF-03"], "US-064"),
    ("FR-INC-11", "WHEN an incident is created, the system SHALL persist it first and then push a notification over WebSocket to the assigned Guide and all online Operators and Admins within 2 seconds, and send an email; clients offline at that time SHALL reconcile on reconnect.", [23], ["MF-03"], "US-058, E03-7, S9-Q9"),
    ("FR-INC-12", "IF an incident stays `Detected` beyond the configured auto-escalation timeout, THEN the system SHALL send an escalation notification to Operators and Admins.", [57], ["MF-03"], "05-main-flows MF-03 parameters"),
    ("FR-INC-13", "WHEN a Guide or Operator submits a response note, the system SHALL append it to the incident's audit trail attributed by role.", [17], ["MF-03"], "US-063"),
    # --- Monitoring
    ("FR-MON-01", "The system SHALL render the live map with MapLibre GL over the configured Goong Maps style, with markers styled by device status.", [14], ["MF-04"], "US-055, D-012"),
    ("FR-MON-02", "The system SHALL deliver live position, telemetry and incident updates over one authenticated WebSocket connection per client, subscribed on the server only to the trips the caller's role may read.", [14], ["MF-04"], "US-053, 05-main-flows MF-04"),
    ("FR-MON-03", "WHILE a device has been silent beyond the configured stale threshold, the system SHALL display it as stale with its last-seen time.", [14, 56], ["MF-04"], "BR-15, E04-1, US-056"),
    ("FR-MON-04", "WHILE a gateway has not synced beyond the configured gateway-stale threshold, the system SHALL show its connectivity indicator as stale on the main dashboard.", [14, 53, 56], ["MF-04"], "US-065, E04-2"),
    ("FR-MON-05", "IF a position lies outside the configured bounds or implies an implausible jump, THEN the system SHALL reject it, log it and not plot it.", [13, 14], ["MF-04"], "BR-16, E04-4"),
    ("FR-MON-06", "WHEN the browser loses the WebSocket, the system SHALL show a reconnecting indicator, reconnect automatically and resynchronize state on reopen.", [14], ["MF-04"], "E04-3"),
    ("FR-MON-07", "IF the map provider is unreachable or rejects the key, THEN the system SHALL show a map error state and keep the device and incident panels working.", [14], ["MF-04"], "E04-6"),
    ("FR-MON-08", "The system SHALL show battery percentage and relative last-seen time on each device marker.", [14], ["MF-04"], "US-056"),
    ("FR-MON-09", "The system SHALL show active incidents in a panel beside the map, filterable by status, highlighting non-closed incidents, with `Suspected` ones visually distinct.", [14], ["MF-03", "MF-04"], "US-066, US-088"),
    ("FR-MON-10", "The system SHALL show Admins a system health view of every gateway's connectivity and audit-log volume by trail.", [53], ["MF-04"], "US-073"),
    # --- Billing
    ("FR-BILL-01", "WHEN a rental's inspections complete, the system SHALL compute the charge as base rate plus late fee plus damage fee minus deposit, applying the deposit before any balance is charged.", [11], ["MF-05"], "BR-17"),
    ("FR-BILL-02", "WHEN check-in is later than the agreed return time plus the configured grace period, the system SHALL compute a late fee at the configured rate as its own invoice line.", [24], ["MF-05"], "BR-18, US-035, E05-1"),
    ("FR-BILL-03", "WHEN an inspection carries a damage report, the system SHALL compute a damage fee from the configured damage-fee schedule and link it to that report.", [25], ["MF-05"], "US-036, E05-2"),
    ("FR-BILL-04", "WHEN charges are computed, the system SHALL issue exactly one immutable invoice per rental itemizing base, late and damage charges, with corrections only as documented adjustments.", [11], ["MF-05"], "US-068"),
    ("FR-BILL-05", "The system SHALL refuse to move a rental to `Closed` while a payment balance is outstanding.", [11, 12], ["MF-05"], "BR-19, E05-4"),
    ("FR-BILL-06", "IF the damage fee exceeds the deposit, THEN the system SHALL consume the deposit and invoice the remainder, and SHALL never produce a negative refund.", [11], ["MF-05"], "BR-20, E05-5"),
    ("FR-BILL-07", "The system SHALL process payments through an internal sandbox with states `Pending`, `Paid` and `Failed`, mark every transaction `sandbox: true`, label it as sandbox in the API and the UI, and let only the billing module change payment state.", [12], ["MF-01", "MF-05"], "US-069, S9-Q22"),
    ("FR-BILL-08", "WHEN a fee waiver above the configured threshold is requested, the system SHALL require approval by a staff member other than the inspector of that device.", [44], ["MF-05"], "BR-21, E05-7"),
    ("FR-BILL-09", "WHEN a Customer booking is confirmed, the system SHALL collect rental fee and deposit into sandbox escrow; WHERE a rental has no booking, an Operator SHALL record the payment.", [12], ["MF-01"], "S9-Q8, Q60 (P)"),
    ("FR-BILL-10", "The system SHALL compute the deposit from the configured tier for the plan, pack, device quantity and device version.", [7, 12], ["MF-01"], "Q61 (P)"),
    ("FR-BILL-11", "The system SHALL let an Admin configure base rates per package, device type and pack, discounts, deposit tiers and fee schedules, and SHALL apply a change only to agreements generated after it.", [50], ["MF-05"], "US-067, Q63 (P)"),
    ("FR-BILL-12", "IF a payment fails, THEN the system SHALL keep the balance outstanding and visible to the Customer and Operators and SHALL write no partial settlement state.", [12], ["MF-05"], "E05-4"),
    ("FR-BILL-13", "The system SHALL provide device-utilization and incident response-performance reports over a selectable date range, derived from existing records and exportable as CSV, with MTTA and MTTR computed from the incident audit trail.", [52], ["MF-03", "MF-05"], "US-071, US-072"),
    # --- Configuration
    ("FR-CFG-01", "The system SHALL read every business parameter registered in the Configuration Matrix from configuration, and a change SHALL take effect without a redeploy.", [19], ["X"], "D-015, BR-23"),
    ("FR-CFG-02", "WHEN a business parameter changes, the system SHALL record the old value, new value, actor and UTC time in an append-only audit trail.", [19, 20], ["X"], "Q46 (P)"),
    ("FR-CFG-03", "The system SHALL hold the map provider, style URL, key and default viewport in configuration.", [19, 14], ["MF-04"], "D-012, D-015"),
]

MF_NAMES = {
    "MF-01": "Booking → Rental → Trip Preparation",
    "MF-02": "Field Data → Offline Gateway → Cloud Synchronization",
    "MF-03": "SOS → Incident → Emergency Response",
    "MF-04": "Real-Time Trip Monitoring",
    "MF-05": "Return → Inspection → Billing → Maintenance",
    "X": "Cross-cutting: administration and access",
}
